### ISSUE TITLE
mirror ubuntu focal repo for local install

### ISSUE THREAD

**Issue by Abraka** [lbr38/repomanager#101]
Hello, I sucessfully install repomanager with docker, but now Im not abble to find out how to add ubuntu focal repo to begin synchronisation with http://archive.ubuntu.com/ubuntu/.

This is in my source list:
deb http://archive.ubuntu.com/ubuntu/ focal main restricted universe multiverse
deb http://security.ubuntu.com/ubuntu/ focal-security main restricted universe multiverse
deb http://archive.ubuntu.com/ubuntu/ focal-updates main restricted universe multiverse

How to configure repomanager to sync all this repos into my docker?

**Comment by lbr38** [comment]
Hello Abraka

I tested with the ubuntu repos you specified and it works fine. 

Before, you have to declare a new source repo in repomanager to be able to sync it.

I just identified an issue with extracting the ubuntu archives files, you will need to install the **xz-utils** package in the docker container (I will fix this in the next release).

0 - Enter the docker container and install the **xz-utils** package:

```
docker exec -it repomanager /bin/bash
apt-get install xz-utils
exit
```

1 - Use the **Manage source repos** button to create a new source repo:

Add the **ubuntu** repo:

Package type: **deb**
Name: **ubuntu**
URL: http://archive.ubuntu.com/ubuntu/**

If you got the ubuntu repo public key, you can import it.

Do it again for the **ubuntu-security** repo:

Package type: **deb**
Name: **ubuntu-security**
URL: **http://security.ubuntu.com/ubuntu/**

Source documentation: https://github.com/lbr38/repomanager/wiki/05.-Manage-sources-repositories#add-a-new-source-repo

2 - You can now sync the **ubuntu** or the **ubuntu-security** repo using the **Create a new repo** button. e.g:

Package type: **deb**
Repo type: **Mirror**
Source repo: **ubuntu**
Custom repo name: (leave empty to use **ubuntu**)
Distribution: **focal**
Section: **main**
If you imported the ubuntu repo key, leave the **Check GPG signatures** option checked.

Then do it all again for the **restricted** section, and again for the **universe** section, and again for the **multiverse** section... as repomanager can only sync one section at a time.

Source documentation: https://github.com/lbr38/repomanager/wiki/02.-Operations-on-repositories#create-a-mirror-repository

Let me know if you need more help.

**Comment by Abraka** [comment]
Wohou, after xz-utils install synchronisation start working, great.

Few suggestios if I may:
1. preconfigured repos option...there are few top distros from apt or rpm world and it would be nice to have a list-option when adding new repo to just choose from some basic options...lets say ubuntu, debian, almalinux, fedora for example. It would be a great start for newbies like me to have a possibility to choose last two-three version of distro like ubuntu 20,22,23. All these repos have repo key in default-specific location, so It should by part of default repo definition list.
2. Section part needs to have ability to specifi a multiple section, so you dont need to create repo for each of them, let repomanager handle sync part but lets not confuse admins and configuration, keep it clean and simple. One repo with all sections is a must.
3. visualise ...would be a nice to have more info like system load, current download speed....

Thats all for now, Iv got possible more, but lets have a easy start :)

**Comment by lbr38** [comment]
Thanks for the suggestions!

1. Already thinked of it. I've already started making a list of source repos that will be shipped by default in a fresh installation. This will be part of a future release.

2. Also already thinked of it. But it's not planned for development yet because it's a major change that requires rethinking the mirroring process and right now I'm trying to focus on improving the UI and the browsing. But be sure that there will be changes in the future on this point.

3. That could be some interesting information indeed. I take note and will see what can be done.

Thank you for your feedback and do not hesitate to give me more in the future, it is very valuable!

**Comment by Abraka** [comment]
> 1. Already thinked of it. I've already started making a list of source repos that will be shipped by default in a fresh installation. This will be part of a future release.

Perfect!, just to point out...there is no need for you to manage hundreds of public repos, just give users some basic 10-20 repos, which is solid base for anybody and then its easy for users to add more if they need. This will be a dynamic feauture which will grow with time, thats for sure.

> 2. Also already thinked of it. But it's not planned for development yet because it's a major change that requires rethinking the mirroring process and right now I'm trying to focus on improving the UI and the browsing. But be sure that there will be changes in the future on this point.

Great, in the end I should be able to point my apt at my local PC to the repomanager in the same way as original:
deb http://repomanager.local/repo/Ubuntu-Focal/focal/main_preprod focal main **+ restricted universe multiverse**

> 3. That could be some interesting information indeed. I take note and will see what can be done.
> Thank you for your feedback and do not hesitate to give me more in the future, it is very valuable!

You can count on it, I will not hesitate with my feedback :)
To gave things a priorities, I would say that 2. is most important as it will propably change a lot internally, then 1. for sure.
Thank you very much for great response.
