### ISSUE TITLE
CREATE A NEW REPO

### ISSUE THREAD

**Issue by Abraka** [lbr38/repomanager#106]
Few suggestions/observations:
Even with new predefined list is adding new ubuntu repo very confusing for us newbies. When you define new source repo there should be just clearly defined items like debian-10,debian-12, ubuntu-focal, ubuntu-jammi etc, no section or whatever.
If I as end user want to download ubuntu-focal, I want just pickup item ubuntu-focal from predefined list and thats it, no section, no nothing else. Expected result from this should by getting everything you get from default source list in new installation of ubuntu-focal.
Also name convection in RPM section is very conmfusing, there should be Almalinux-8, Almalinux-9. Names like baseos, extras, apstream, updates....as end user I dont have idea what it is, to what it belong and why I needed or if I even needed.
Again name convection should be something like this...Almalinux-9, Almalinux-9-extra. Maybe better Almalinux-9-Full, just give me all for x64. Same as with deb section...I expecting from Almalinux repo to give me all from all default defined repos from default new installation Almalinux.
RM can do much more, but for example for my needs I just want tool where I in simple way define new distro, RM will download it and finally I just define new repos in target installation. Thats it and I guess that this will be main point for majority of potentional interested users.

**Comment by lbr38** [comment]
Hello,

Thank you for your improvement suggestions!

Package repositories are complex concepts, and Repomanager was not designed for beginners but rather to facilitate the creation of mirrors without the need for command lines. The goal is not to simplify the architecture of the repositories but simply to copy them locally as they are from the source.

I believe it is essential to have at least some understanding of Debian and RHEL/CentOS repositories.

- Information regarding Debian repositories: https://wiki.debian.org/SourcesList#Commonly_used_package_sources
- Information regarding RHEL repositories: https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/installing_managing_and_removing_user-space_components/using-appstream_using-appstream

There will likely be future improvements, but as explained earlier, it is a complex overhaul that requires a long phase of reflection and testing. Currently, it is summer, and I am mainly occupied with enjoying the nice weather, and unfortunately, there are no other people in the development team. Patience :)

AlmaLinux and Rocky Linux repositories are based on CentOS repositories, so I believe it is appropriate to use the following predefined repositories:

For CentOS 8 / Alma Linux 8 / Rocky Linux 8:

- appstream-8
- baseos-8
- epel-8
- extras-8

For CentOS 9 / Alma Linux 9 / Rocky Linux 9:

- appstream-9
- baseos-9
- epel-9
- extras-common-9

This should provide most of the basic packages.

**Comment by Abraka** [comment]
I get your point, my problem is with complexity of entire proces. If you target user base is few advanced devops or sysadmins with needed knowledge and needed time for study and understand things around this problematics, it is ofcourse ok. But if you want wider adoption of RP from user base which do not want or its intersted in investing lot of time and work into this, theres need to be some changes how to address things.
So souggestion...you dont need change the way distros and their repository works...ofcourse, but cover this proces and underlaying problematics with simple - lets call it "newbie mirror wizard" which simply through few screens give a end user easy and comfort way to add local mirrors. All magic will be hidden and end user just choose from predefined list of distros+extras(there should by a text with descriptions of this extras) just like shopping card...then next screen...choose how freqwently run sync...day,week etc. and the end show repo info for new mirror a direct user on operation page. Also would be nice to have just general estimates about needed space for chosen mirror in predefined list.
So this could by a way for much vider adoption if you want such a thing.
