### ISSUE TITLE
Improvement: Larger default upload_max_filesize in php.ini

### ISSUE THREAD

**Issue by rolffujino** [lbr38/repomanager#122]
Currently the default php.ini size for:
> php.ini => upload_max_filesize (must be equal or higher than the file's size you're attempting to upload)

Is rather impractical and small at 2M, by default I would suggest upping this to match the nginx size of 32M.

**Comment by lbr38** [comment]
Hi

This setting is customizable when running the docker image:

`MAX_UPLOAD_SIZE` Max upload size in MB (default 32). Increase this value if you want to upload large packages to your repos.

```
docker run -d --restart always --name repomanager \
        -e FQDN=repomanager.example.com \
        -e MAX_UPLOAD_SIZE=32M \
        -p 8080:8080 \
        -v /etc/localtime:/etc/localtime:ro \
        -v /var/lib/docker/volumes/repomanager-data:/var/lib/repomanager \
        -v /var/lib/docker/volumes/repomanager-repo:/home/repo \
        lbr38/repomanager:latest
```

I fixed a bug relating to upload in the latest version, have you installed the latest version? I tested it myself and uploading larger packages works correctly.

If you use a nginx reverse proxy in front, also consider increasing the value of `client_max_body_size` in the vhost configuration (I will specify this in the documentation).

**Comment by rolffujino** [comment]
@lbr38 I had not asked my team to alter that setting, sorry for troubling you, but thank you for pointing this out!
