### ISSUE TITLE
Container logs keeps printing "Getting settings..."

### ISSUE THREAD

**Issue by Cloud-Kid** [lbr38/repomanager#125]
Hi all ! 

Since I started using the container I keep getting a "Getting settings..." message every seconds constantly in container logs, is this a bug or did I just forgot something during deployment ?

![Capture d’écran 2023-10-31 093408](https://github.com/lbr38/repomanager/assets/49484832/35e7ac28-6eb2-42a5-bc8b-a622361b8223)

**Comment by lbr38** [comment]
Hi

This is not a bug, it is the output of the Repomanager service which is running in the background. Every ~5 seconds it retrieves the general configuration of Repomanager and performs actions based on it.

Normally these messages should not appear unless you display the container logs.

**Comment by Cloud-Kid** [comment]
All right thanks for your answer !
