### ISSUE TITLE
Some issues adding an external repo

### ISSUE THREAD

**Issue by Cloud-Kid** [lbr38/repomanager#127]
Hi, hope you are doing good ! 

I had some issues adding my first external repo (Not in the predefined list) and I'd like to share them with you.
But first I'd like to thank you again for your work as I was not able to find a software like this elsewhere.

That being said here are some thoughts :

1. Firstly, the UI is pretty and looking pretty easy but when you really try to add repos the UX is not that intuitive
2. The Wiki is pretty helpful but the "Adding a new repo" part is lacking some informations IMO
3. The predefined repos worked flawlessly so nothing to say about that
4. It may be intersting to add the possibility to add "distribution" tags in your predefined list using the GUI (Instead of entering it manually)

For the following issues I had, it was with trying to add a Debian 9 (Stretch) repo to repomanager but their may global issues

5. I can't add the GPG key for Stretch (Using URL orl Copy/Pasting it) but it worked using another key for another repo
![Capture d’écran 2023-11-08 094145](https://github.com/lbr38/repomanager/assets/49484832/c05e597f-7705-4fae-be97-2ba2396ead9e)
![Capture d’écran 2023-11-08 094019](https://github.com/lbr38/repomanager/assets/49484832/dcdc6981-9427-4016-b455-ab0a6e113e1a)

6. I encounter some random Curl errors while trying to download repos sometimes but never at the same line, I keep you updated if I manage to find why
![Capture d’écran 2023-11-08 095014](https://github.com/lbr38/repomanager/assets/49484832/be1d6204-cfe9-4a9b-abb0-69f20fcdcb66)

Hope this can help to improve your software ! 
Take care, 
Cloudkid

**Comment by lbr38** [comment]
Hello,

Thank you again for your interest in this product, it's very encouraging!

I know what you mean about the UX/UI, I appreciate the feedback. However, UX/UI is a distinct profession, and I am neither a developer nor a professional designer (just a sysadmin). I often find it hard to strike the right balance in terms of display, and you can't imagine how much I struggle whenever I have to work on the frontend (HTML/CSS/JS). It sometimes takes me hours for minor improvements :') 
I will see what I can do.

To address the issue, could you please provide the GPG key you want to import? I will try to reproduce it on my side. 
There seems to be an issue with your GPG keyring (second screenshot). Is this error also present in other mirroring operations?

Regarding the empty curl errors, it's not normal for them to be empty. I will check if I can find a fix to make them display the actual problem, so we can identify the root cause (third screenshot).

**Comment by Cloud-Kid** [comment]
Thanks for taking all of that into account quickly ! 

I'm also a systadamin but I have a bit of knowledge about UI/UX I may try to get my hands dirty and help you by contributing to your project.

Sure, [here is the GPG key](https://archive.debian.org/debian/dists/stretch/Release.gpg) on debian website

Hum, you are right about the curl request error, maybe we can check the logs in the containers directly ?

**Comment by lbr38** [comment]
Hi 

Just released the new version, can you check if this helps you with retrieving the correct GPG key?

**Comment by Cloud-Kid** [comment]
Hey,

I followed your instructions, they are very helpful indeed ! I don't know that munch about repos & GPG, I thought it was easier that but hey, we learn everyday !

It know works using GPG, I can import new keys and see logs if it fails, thanks !

Just a last word regarding previous requests, I saw that you added strecth as a distro, but I think it will be easier if you could add your own using a form !

**Comment by Cloud-Kid** [comment]
I still can't download big external repos (More than a few GBs), the download stop with an empty curl error, maybe you can add the curl logs debugging or where can I find the logs in the container directly ? (See the third screenshot from early in the discussion)

**Comment by lbr38** [comment]
Can you please provide:

- The source repo URL 
- The distribution and section

I will try to reproduce on my side. 

I can't find why the curl error is empty, it normally should print something.

**Comment by Cloud-Kid** [comment]
All right, 

I still try to fetch Debian 9 ([Stretch](https://archive.debian.org/debian/dists/stretch/)) repos, 
the repo URL I use in repomanager is [this one](https://archive.debian.org/debian/) > stretch > main
It start correctly but fails randomly at differents download numbers with an empty cURL error.
Again, maybe it's linked to my environment but I still can't figure why this can happen.

I managed to downloads the two other repos (contrib & non-free) by relaunching the download repo task several times and because they are small repos they finally worked, but the big **main** repo always failed before ending.

**Comment by lbr38** [comment]
Okay thanks

If facing the same problem with the `debian-archive > stretch > main` branch, I finally got the empty curl error!!

The error code is `16` and is related to http2 connection:
```
CURLE_HTTP2 (16)
A problem was detected in the HTTP2 framing layer. This is somewhat generic and can be one out of several problems, see the error buffer for details.
```
This explain the reason why the curl error is empty (it can be out of several problems).

I think the root problem is the https://archive.debian.org/debian/ repository. So I have forced the use of http1.1 in the code and now the repository mirror has succeeded.

I will make some speed tests to see if the use of http1.1 does not impact too much the download speed on big repos. If there is no real impact then I will let http1.1 as default.

Maybe you could test that patch on your side and tell me if it works for you too?

1. Enter the container:

```
docker exec -it repomanager /bin/bash
```

2. Edit the `Mirror.php` file:
```
vim /var/www/repomanager/controllers/Repo/Mirror/Mirror.php
```

3. Go to the line `128` and add a new curl option:
```
curl_setopt($this->curlHandle, CURLOPT_HTTP_VERSION, CURL_HTTP_VERSION_1_1);
```

4. Save and relauch your mirror operation.

**Comment by Cloud-Kid** [comment]
I'm at school today but I can try this on Monday, well played for sorting this out ! :0 
Maybe the easiest way to correct this for old repos or some with the same problems is to implement some kid of switch that can enable old version of cURL or the latest one id necessary.
But anyway, if that works I don't mind editing the curl option for some repos if that's necessary.
I'll keep you updated !

**Comment by Cloud-Kid** [comment]
Hi,

The fix seems to work ! I never managed to download more than 10k files but now I do, It really looks like that's it.
Thanks for your help, feel free to close the issue if you don't plan to fix it because I don't think that will cause issues to that many people, but I will leave it like that in case you plan to edit the cURL version or add a button to select it.

Regards, Cloudkid
