### ISSUE TITLE
UI for viewing old operation logs doesn't work

### ISSUE THREAD

**Issue by rolffujino** [lbr38/repomanager#132]
When clicking on one of the operations in the history column, the loading circle is generated on the bottom left, but the page and URL does not update to show the operation and its logs.
Manually grabbing the log name and appending it to this URL does show the log:
http://repomanager.example.com:8080/run?view-logfile=

Issues persists in Chrome and Firefox on Windows 11 and using latest repomanager version.

**Comment by lbr38** [comment]
1. Is there any JS error in your browser console (F12)?

2. Can you check if there are errors thrown by PHP please:

Enter the container:

`docker exec -it repomanager-dev /bin/bash`

Print all the logs:

`tail /var/log/nginx/*error*log /var/lib/repomanager/logs/exceptions -f`

Then click an operation log and see if there are errors.

3. Try cleaning all your cookies.

Thanks

**Comment by rolffujino** [comment]
@lbr38  the UI does work very nicely on my personal desktop when running an instance, so I will blame my VDI for breaking the UI, will close this out.
