### ISSUE TITLE
Uploading DEB package to local repo fails due to lack of section

### ISSUE THREAD

**Issue by rolffujino** [lbr38/repomanager#133]
When trying to upload a DEB package to a local repo, it fails as it complains about a lack of section:
> No section given for 'gc-guest-agent', skipping.
Warning: database 'focal|main|amd64' was modified but no index file was exported.
Changes will only be visible after the next 'export'!
There have been errors!

This was being uploaded from Windows 11 and issues persists on both Firefox and Chrome.

**Comment by lbr38** [comment]
Is there a way you could send me that package? Or somewhere I could download it?

I will try on my side and see what I can do.

**Comment by rolffujino** [comment]
Let me discuss internally, it is a package from a proprietary SaaS solution. I will also continue my investigation, I assumed it was related to Repomanager as it expects a section field in a lot of calls.

**Comment by lbr38** [comment]
This error is thrown by `reprepro` which is the tool I use to build the repository metadata. reprepro is meant to be used with Debian Policy compliant packages so it does a lot of checks.

I assume the `Section` param has been missed in the `control` file when the package was built. Here is an example of a control file with a valid `Section` param: https://github.com/lbr38/awscliv2-deb/blob/main/.github/workflows/packaging/deb/control

I think I could try append `-S` to reprepro to fix this: https://askubuntu.com/questions/441802/reprepro-no-section-given-for-galera-skipping

**Comment by lbr38** [comment]
Can you confirm the latest version (v3.7.7) is fixing this issue, please?
