### ISSUE TITLE
CHange GPG key on the fly

### ISSUE THREAD

**Issue by cfouche3005** [lbr38/repomanager#135]
Is it possible to change the GPG Key ID in the setting page ? When I change it, my repo fail to build because it can't fing the new gpg key. Does auto generate the new key or do I need to provide it and if i need to provide it, where I can place it ?

**Comment by lbr38** [comment]
This is not something that can be done on the fly currently. But if you really want to generate a new key, here's how:

1. Specify a new key Id in the **GPG key Id** field (settings page). The key format must be **xxxx@yyyy**.

2. Enter the container: 

`docker exec -it repomanager /bin/bash`

3. Delete pubring and macros files:

`rm /var/lib/repomanager/.gnupg/pubring.* /var/lib/repomanager/.rpm/.mcs -f`

4. Refresh Repomanager (F5) and test.

**Comment by cfouche3005** [comment]
ok thanks, can you put that into the setting documentation ?

**Comment by lbr38** [comment]
This is done: https://github.com/lbr38/repomanager/wiki/08.-Settings#gpg-signature-key

There is another path you need to delete: ``/home/repo/gpgkeys/*`` This directory stores the public key for the clients to retrieve.

Closing this issue & adding the "key change on the fly" in my TODO list ;-)
