### ISSUE TITLE
Feature Request: rsync support

### ISSUE THREAD

**Issue by sgnsys3** [lbr38/repomanager#143]
Hi

Do you have any plans to support the rsync mirror?

Thanks

**Comment by lbr38** [comment]
Hello @sgnsys3 

I don't plan to support rsync at the moment.

Do you have an example repo that would require using rsync rather than curl?

Thanks

**Comment by sgnsys3** [comment]
Hi @lbr38 

For example, ISO mirrors like HBCD, https://www.hirensbootcd.org/become-a-mirror/

**Comment by lbr38** [comment]
Sorry but this is not the purpose of Repomanager to mirror ISO repositories. Even if I make the support of rsync possible, it will never work.

Only deb/rpm packages repositories are covered by Repomanager.
