### ISSUE TITLE
outgoing proxy settings support

### ISSUE THREAD

**Issue by broxio** [lbr38/repomanager#151]
Some of my system has been located in really stricted inbound and outbound policy and only able to access to the world via designate proxy, after dig out through UI seems not able to setup proxy,  do I need to setup in php app ?

**Comment by lbr38** [comment]
Hello 

I can confirm that there is no proxy setting support right now. As I don't know how to set this up easily and I don't have a proxy server to test this functionality, I don't know when it will be developed.

**Comment by broxio** [comment]
​Seems doable since the application using curl based exec call from controller, just how to implement settings properly and make it flexible to use, will keep you post, nice application btw 👍

**Comment by holl595** [comment]
I've raised a pull request that should resolve this, we have had it successfully working behind a http proxy

**Comment by lbr38** [comment]
So just like I said I've improved @holl595's modification and I've integrated the addition of a proxy directly into the global settings (SETTINGS tab).

![image](https://github.com/lbr38/repomanager/assets/54670129/b2762f9f-a38d-4500-a47a-ede380884ff3)


A new docker image has been published with the feature.

@broxio & @holl595 could you update Repomanager to the latest version and confirm that it works well?

**Comment by holl595** [comment]
I have tested the new image this morning and it seems to be working fine
