### ISSUE TITLE
native package

### ISSUE THREAD

**Issue by devza300** [lbr38/repomanager#157]
Could you please add the build to the debian (or rpm) package. In the future, we may include your own repository for repomanager deployment and updates.

Thank you for your work.

**Comment by lbr38** [comment]
Hello
I don't understand your request very well. What package do you need?

**Comment by devza300** [comment]
Hi. Now deploy is presented as a docker container, for easier installation and updating, you can add the build to "repomanager.deb".

**Comment by lbr38** [comment]
Hello

Sorry but that's not possible.

Building deb/rpm packages and taking into account each dependency of each operating system is a real headache.

The docker image is the only way to easily install and update Repomanager without having to worry about the host system.
