### ISSUE TITLE
Feature Request - Ability to choose to skip rpms who fail gpg check

### ISSUE THREAD

**Issue by JamesXNelson** [lbr38/repomanager#164]
While mirroring temurin jdk from adoptium, we hit issues w/ some rpms that reliably failed signature checks.

Rather than break the whole mirror, it would be nice to have a checkbox to simply skip any files that failed their checks.

Obviously better to get upstream to not publish junk, but we live in an imperfect world. ^-^

**Comment by lbr38** [comment]
Can you give me the source URL, the release version and the architecture(s) you're trying to mirror please?

I'll see what I can do.

**Comment by lbr38** [comment]
Currently adding and testing two new settings that should help you handle rpm with invalid signature:

- When package signature is missing
- When package signature is invalid

With three possible options: 

![Capture d’écran du 2024-05-08 14-50-32](https://github.com/lbr38/repomanager/assets/54670129/d8272c15-abe3-4a81-9195-6efdb4cc87e7)

This is working fine with adoptium repo. Should be available in the next release.

**Comment by JamesXNelson** [comment]
wow! you rock!!

Sorry I didn't get you those urls.

I'll make sure to pull this and try it out when we do the next scheduled mirroring.

**Comment by JamesXNelson** [comment]
for deb (the Release vs InRelease) bits:
`https://packages.adoptium.net/artifactory/api/gpg/key/public`
`https://packages.adoptium.net/artifactory/deb jammy main`

**Comment by lbr38** [comment]
Hello

Please update your docker image to the latest version `4.1.0`

You will be able to skip rpms with missing/invalid signature by using the `When package signature is missing` and `When package signature is invalid` settings from the SETTINGS tab.

Let me know if it's all good. 

Thanks!

**Comment by lbr38** [comment]
I guess this is OK

Closing
