### ISSUE TITLE
Docker cannot login 

### ISSUE THREAD

**Issue by linyzeng** [lbr38/repomanager#166]
Dockerfile needs to set the user of /var/lib/php/sessions to www-data:repomanager

**Comment by lbr38** [comment]
Hello

Default permissions are valid:

![image](https://github.com/lbr38/repomanager/assets/54670129/fe2f4632-8793-4bc6-b7a8-9f2fa395bbd4)

www-data has the right to write into /var/lib/php/sessions/ directory, I don't know why I should modify anything unless you give me a good reason to do so.

Please give more details on your issue.

**Comment by linyzeng** [comment]
No problem! My apologies for the incorrect feedback. Everything is working fine.

I tested it on a CentOS machine and it worked fine.
 
Upon comparison, I found that the issue was with the default umask of my operating system(Anolis OS), which is set to 0027 and can cause this problem.  Most operating systems default umask is 0022.
