### ISSUE TITLE
Any way to sync RedHat repos (Using subscribtion-manager) ?

### ISSUE THREAD

**Issue by Cloud-Kid** [lbr38/repomanager#169]
Hello there,

Is there any way to use the tool for Rhel servers using official RedHat suscription ? I don't know munch about RedHat suscription but I'm sure there may be a way.

Thanks !

**Comment by lbr38** [comment]
Hello

I'll see what I can do and keep you in touch

**Comment by FalconXC4** [comment]
Yes please this is a big issue for me too!

**Comment by lbr38** [comment]
I have find a way to sync those repositories just let me a bit more time to test and release the version.

Spoiler: you will need to register a host to Redhat (Redhat subscription) then retrieve the content of your Redhat private key and certificate, and also the Redhat CA certificate. You will find their path in `/etc/yum.repos.d/redhat.repo`.

![image](https://github.com/lbr38/repomanager/assets/54670129/7e4afb5c-b62f-4171-b4eb-83d9ebbedc61)

**Comment by lbr38** [comment]
Okay I released version `4.2.0`, here are the steps to sync Redhat repositories with Repomanager. This is a manual process for now, I will see in the future how to do all of this through the web interface when I have more time to work on it.

1. You will need a Redhat8 or Redhat9 host/server with a valid subscription (see https://access.redhat.com/solutions/253273)

2. Once your host is registered, you should have access to Redhat rpm repositories (you can try with yum update).
Just for you to understand: Redhat repositories are private and only accessible with a certificate and private key (this is what subscription provides). Now that you are registered, you can retrieve the certificate and private key content and import them into Repomanager to be able to sync Redhat repositories (see below).

3. From your registered host, retrieve the certificate, private key and Redhat CA certificate content. You can find their location in `/etc/yum.repos.d/redhat.repo`:

![image](https://github.com/lbr38/repomanager/assets/54670129/f342159a-b878-4754-b35b-92437f382976)

Simply `cat` the content of each file and copy/paste it to a text aditor (lines from -----BEGIN PGP PUBLIC KEY BLOCK----- to -----END PGP PUBLIC KEY BLOCK-----).

```
cat /etc/rhsm/ca/redhat-uep.pem
cat /etc/pki/entitlement/733946906105629479-key.pem
cat /etc/pki/entitlement/733946906105629479.pem
```

4. Now go back to your Repomanager server and enter the docker container:
```
docker exec -it repomanager /bin/bash
```

5. Create a redhat directory:
```
mkdir /var/lib/repomanager/ssl/redhat
```

6. Put the certificate, private key and CA certificate content in it:
```
cd /var/lib/repomanager/ssl/redhat
```

```
vim certificate.crt # paste the content of the certificate
```
```
vim private.key # paste the content of the private key
```
```
vim ca-certificate.crt # paste the content of the CA certificate
```

7. Set permissions:
```
chown -R www-data:www-data /var/lib/repomanager/ssl/redhat
chmod 400 /var/lib/repomanager/ssl/redhat/*
```

8. Go to the Repomanager web interface, open the `Manage sources repos` panel, you will find the two main Redhat repositories named `redhat-baseos` and `redhat-appstream`. Edit each of them and provide the path to the certificate, private key and CA certificate:

![image](https://github.com/lbr38/repomanager/assets/54670129/7ee105e7-b817-45f3-9813-fd4bd06f8e4d)

9. Save and try to sync the repositories.

Tell me if it is clear and I will add this to the official documentation. Thanks!

**Comment by FalconXC4** [comment]
Hi, 
Thank you very much for the update! Unfortunatly I do not have the SSL fields in the "Manage sources repos" panel.
Do you have any advice?

![image](https://github.com/lbr38/repomanager/assets/173842485/62d58f67-5c5a-415c-84cb-33f9b4f55446)
[...]
![image](https://github.com/lbr38/repomanager/assets/173842485/e503db37-e63d-4669-8047-21a43a7b7e62)

**Comment by lbr38** [comment]
The SSL fields are visible when editing an existing source repository:

![Peek 27-06-2024 16-35](https://github.com/lbr38/repomanager/assets/54670129/5260469b-8514-4a4c-8c37-5e3a2620f516)

You should see the redhat-baseos and redhat-appstream (4.2.0 imported them). You can add new repositories but you will have to edit them to see the SSL fields (I want to keep the process of "adding" very simple with not too much advanced parameters).

**Comment by Cloud-Kid** [comment]
Okay ! Thanks for the info, I couldn't find it either ! It's not straightfoward but maybe it can be edited as a dropdown menu to keep things coherent while keeping it nice and tidy

**Comment by FalconXC4** [comment]
Hi,
Thank you very much, tested yesterday and it works like a charm!

**Comment by Cloud-Kid** [comment]
It works ! 
I still think it can appear as a dropdown or a checkbox for like "advanced options" at creation but feel free to close the issue if you do not plan or have tlme to edit it.
Thanks again !

**Comment by Cloud-Kid** [comment]
For information to anyone trying to sync Redhat repos prior to Repomanager 4.12, here is a little script that I use to automatically copy the constantly renewed Redhat certificates from the host to repomanager container shared storage.

```
#!/bin/bash

## Usage :
### One time execution :
# nohup /path/to/your/script.sh &

### As a systemctl daemon
# sudo nano /etc/systemd/system/cert-monitor.service

# [Unit]
# Description=Red Hat Subscription Certificate Monitor

# [Service]
# ExecStart=/path/to/your/script.sh
# Restart=always

# [Install]
# WantedBy=multi-user.target

# sudo systemctl daemon-reload
# sudo systemctl enable cert-monitor.service
# sudo systemctl start cert-monitor.service


# Path to the Red Hat subscription certificates
CERT_DIR="/etc/pki/entitlement"

# Path to the destination where the certificates will be copied
DEST_DIR="YOUR PATH"

# Function to copy certificates
copy_certificates() {
    # Find the key file (ends with -key.pem) in CERT_DIR only
    KEY_FILE=$(find $CERT_DIR -maxdepth 1 -type f -name '*-key.pem')

    # Find the certificate file (ends with .pem but not -key.pem) in CERT_DIR only
    CERT_FILE=$(find $CERT_DIR -maxdepth 1 -type f -name '*.pem' ! -name '*-key.pem')

    # Copy the files with new names if they exist
    if [[ -f $KEY_FILE ]]; then
        cp $KEY_FILE $DEST_DIR/certificate-key.pem
        echo "Copied $KEY_FILE to $DEST_DIR/certificate-key.pem"
    else
        echo "Key file not found"
    fi

    if [[ -f $CERT_FILE ]]; then
        cp $CERT_FILE $DEST_DIR/certificate.pem
        echo "Copied $CERT_FILE to $DEST_DIR/certificate.pem"
    else
        echo "Certificate file not found"
    fi
}

# Monitor the CERT_DIR for changes and run copy_certificates function
while inotifywait -e modify,create,delete $CERT_DIR; do
    copy_certificates
done
```

You can run this script as a systemctl daemon as explained in the script comments.

**Note that this script will not work after Repomanager version 4.12** as the certificate content is no more exposed to the container as file but as a text entry in the app directly.

A new script should be available soon for this usecase.

Regards, 
Cloudkid
