### ISSUE TITLE
Allow user to cancel a ongoing task

### ISSUE THREAD

**Issue by Cloud-Kid** [lbr38/repomanager#170]
Hey,

Another improvement that I think should permit more control on your app is to allow the user to cancel a sync in progress or that is stuck.
I think it can be a great feature to implement if you have time !

Regards, Cloudkid

**Comment by FalconXC4** [comment]
Not obvious but you can already do it by hovering the TASKS tab, then a cross apears on the right of the task :
![image](https://github.com/lbr38/repomanager/assets/173842485/9663c0f5-767a-4532-b1f4-ff68f662b730)

**Comment by lbr38** [comment]
Yes there is already a way to stop tasks as @FalconXC4 showed it, but if it is not obvious it means it should to be improved.

I will see to add a stop button in the tasks tab.

**Comment by Cloud-Kid** [comment]
@FalconXC4 True !

Thanks for your output, I was looking into the tasks tab directly and I should it can be improved, that's a good point @lbr38 

Thanks again, 
Regards

**Comment by lbr38** [comment]
`4.2.1` version released. Added a new button in the tasks tab to stop running tasks.

Also added a more explicit message on task log when it has been stopped.
