### ISSUE TITLE
Feature request: Disable authentication

### ISSUE THREAD

**Issue by yeyeoke** [lbr38/repomanager#172]
Hi, thanks for a great project! 

I noticed, and respect, that SSO isn't coming anytime in the near future. In the meantime though, could we get an option to disable authentication? 

That would in my use-case mean that I can simply protect this behind my IDP (Authentik) and delegate access via groups. An environment variable like DISABLE-AUTH=true would be more than sufficient.

**Comment by lbr38** [comment]
Hello

Sorry but I can't do this as this will break the app. Some functions are limited to admins (e.g. executing operations on repositories) and requires to be authenticated.

I may take a look at SSO implementation in the future but you know I do things at my level and I don't have an army of developers behind me, so I can't positively respond to all feature requests, especially when it comes to save 1 mouse click at the expense of hours of implementation and testing. I'm sorry to say this, but if people want a solution that can fully integrate into their IT system, they may look at paid solutions (i.e. Redhat Satellite & co). 

I will now close this issue as I won't integrate SSO, LDAP, or modify the authentication for now. But be sure that I keep that in mind.
