### ISSUE TITLE
$basearch variable not replaced during sync

### ISSUE THREAD

**Issue by Cloud-Kid** [lbr38/repomanager#177]
Hey,

Here is a issue, it seems odd because it doesn't looks like it happen on other repos, but in my case, on Redhat repos while trying to sync the "$basearch" is not replaced and fail to sync. In the other hand, if I set the full repo URL without the variable it works and the "$releasever" is replaced successfully.

I tried it with two RHEL repos.

It looks like a bug because it's not remplaced before the sync, but I may be wrong.

![image](https://github.com/lbr38/repomanager/assets/49484832/b45c96a5-8adc-47f2-9c98-c86bf577758a)

Thanks again for your work,
Regards

**Comment by lbr38** [comment]
Hello

I reproduced the bug, I will provide a fix soon. Thanks!

**Comment by lbr38** [comment]
This should be fixed now.

**Comment by Cloud-Kid** [comment]
It's now properly replaced ! Thanks and good job :D
