### ISSUE TITLE
Task stuck at "Retrieving package list"

### ISSUE THREAD

**Issue by Cloud-Kid** [lbr38/repomanager#182]
Hi again,

While trying to sync the RedHat appstream repo (Only this one) I have the following error :

![image](https://github.com/user-attachments/assets/077077c1-e9e1-479c-9612-de0b2972a975)

Tested on multiple repomanager versions including the latest. I tried multiple times, waiting 4+ hours but I really think nothing is happening (Also minimal CPU usage is being used).

Let me know if you have any ideas.

Regards, Cloudkid

**Comment by lbr38** [comment]
Same as https://github.com/lbr38/repomanager/issues/119 (see my latest message). You task has reached php memory limit and the script exited.

In most case it should have printed an error message in the app but there is a bug where sometimes php doesn't even have enough memory to print the error itself. I just patched this bug today but I need more tests to release a new version.

For now you can stop the task (stop button) if not already done and dedicate more RAM to your docker instance. In the linked issue we saw that about 4GB+ were required to parse the huge packages list of Oracle Appstream repo, I think this might be quite the same for RHEL Appstream. I know this is a lot but I don't know why the xml lib is consuming so much RAM.

Thanks for reporting.

**Comment by Cloud-Kid** [comment]
That's right indeed, I just increased the memory limit to 1024 and the task is running successfully. Thanks for the tip !

I'll check the discord soon !
