### ISSUE TITLE
Feature Request: Update without create new branch

### ISSUE THREAD

**Issue by nikolaidrag** [lbr38/repomanager#187]
Hello, we need the ability to update the repository mirror within itself, without creating a new branch, or so that after creating a new branch the old one is deleted.

**Comment by Cloud-Kid** [comment]
Hey,

I think there is a misunderstanding of the usage of the tool, each repo contains "snapshots" of the repo at a certain time, so you don't update the "mirror" you create a new snapshot of this mirror and then you can point your "preprod" or "prod" environment that will always use the same URL to access it.

Each of the steps can be automated and scheduled so it can automatically add new repos snapshots and set the retention period to your desired length.

Regards, Cloudkid

**Comment by nikolaidrag** [comment]
I mean sync snapshot without create new snapshot, or the ability to automatically set the lifetime of snapshots for automatic cleaning.

**Comment by lbr38** [comment]
Hello

Release version `4.7.0` is now out and it allows you to set snapshot retention to 0. I hope this will suits your needs.

**Comment by nikolaidrag** [comment]
Thanks, that's what I needed.
