### ISSUE TITLE
Faster adoption

### ISSUE THREAD

**Issue by Abraka** [lbr38/repomanager#203]
Hi there,
I would like to suggest that having more defined distros by default will result in faster adoption of repomanager. With rpm and deb support there are few top players in the filed, so having them defined from start would by definitely helpful. Rpm = AlmaLinux, RockyLinux, Fedora, OpenSuse, Deb = MXLinux, LinuxMint, KDE neon, KaOS... for example.
And any thoughts on supporting repositories of Arch Linux?

**Comment by lbr38** [comment]
Hello,

You're right, I will look into adding the repositories of the most common OSes (Alma, Rocky, Fedora, etc.). I am not sure it is relevant to add the less common OSes (KDE neon, KaOS, etc.).

This list of predefined repositories needs to be maintained, updated (if repositories change their URL or GPG key, for example), and tested regularly, and I don't have the time to do that. If people need additional repositories in the list, they should add them via the Manage sources repos panel.

Regarding Arch Linux repositories, it is somewhere on my to-do list, but for now, I have neither studied how Arch repositories work nor how to synchronize them. If you have any information/links on the subject, I would appreciate it.

**Comment by Abraka** [comment]
> Hello,
> 
> You're right, I will look into adding the repositories of the most common OSes (Alma, Rocky, Fedora, etc.). I am not sure it is relevant to add the less common OSes (KDE neon, KaOS, etc.).
> 
Well we will left the decision about that to you, distrowatch is your best friend in this.

> This list of predefined repositories needs to be maintained, updated (if repositories change their URL or GPG key, for example), and tested regularly, and I don't have the time to do that. If people need additional repositories in the list, they should add them via the Manage sources repos panel.
>
This shoudnt be so problematic, repositories in top distros doesnt change source address that offten and Im sure that users will report it here if those get invalid.

> Regarding Arch Linux repositories, it is somewhere on my to-do list, but for now, I have neither studied how Arch repositories work nor how to synchronize them. If you have any information/links on the subject, I would appreciate it.

Unfortunatelly I dont know much about their repos, but they have an excelent wiki. This https://wiki.archlinux.org/title/Pacman#Repositories_and_mirrors will be a good start if you get some time.

**Comment by lbr38** [comment]
> > Hello,
> > You're right, I will look into adding the repositories of the most common OSes (Alma, Rocky, Fedora, etc.). I am not sure it is relevant to add the less common OSes (KDE neon, KaOS, etc.).
> 
> Well we will left the decision about that to you, distrowatch is your best friend in this.

I think that tools like Repomanager are mainly used to maintain the packages of servers, and I doubt that there are many servers running on LinuxMint in the world. I could be wrong, but I think that most desktop OSes remain connected to the official repositories provided at installation. However, if there is a real demand to add these repositories to the list, I will do it ;)

> Unfortunatelly I dont know much about their repos, but they have an excelent wiki. This https://wiki.archlinux.org/title/Pacman#Repositories_and_mirrors will be a good start if you get some time. Well here it is ... https://wiki.archlinux.org/title/DeveloperWiki:NewMirrors

Thanks for the links, I will check them out!

**Comment by Abraka** [comment]
Well I get your point but on the other side...try to look at it this way...you are a new repomanager adopter and all you see is very few options like ubuntu and redhat...that doesnt look that good or interesting. And of course, expirienced users can add another repos by their choosing but from novice point of view, there is not much going here. 
You can get some good promotion of your work on reddit channels like selfhosters, datahoarders etc. which will a potentionally give you much bigger audience and for this to work, you need offer more from the start.
But ifs entire point of repomanager is tool for few nerds and admins around and you dont have ambition for wide user base, then current setup is propably ok.

**Comment by Cloud-Kid** [comment]
I agree that more repos could be added by default, netherless I also find unnecessary to add distros that are not server oriented like Mint or other desktop OS.

**Comment by Abraka** [comment]
Its a linux distro, you can install desktop on redhat or debian and same way make a server on distro like mint,kaos or arch.
For example having some "desktop" distros will make repomanager more atractive to home lab users. I have few desktop installation at home so having local mirror for LAN is a nice thing to have.

**Comment by lbr38** [comment]
I propose the following solution: I will first add additional repositories (Alma, Rocky, and other common "server OS"), and I will add a feature to import additional repositories. Concretely a button to import a list of additional repositories (desktop OS based on Ubuntu, desktop OS based on Fedora, etc.). The lists will be collaborative (hosted on github) so everyone can modify and maintain it or create new ones. The user will be able to choose which list to import.

I think this is a good compromise for those who want to add additional repositories and those who want to keep only a minimal set of repositories.

**Comment by Abraka** [comment]
Ok, why not.

**Comment by Cloud-Kid** [comment]
Yea a community driven list is definitely a good idea ! Really looking forward to that :-)
