### ISSUE TITLE
Predefined source - almalinux cbr error

### ISSUE THREAD

**Issue by Abraka** [lbr38/repomanager#206]
Hi, youv got an error in cbr link definition https://repo.almalinux.org/almalinux/9/crb/, cbr needs to be in upercase and then its working.

_No reachable URL found. The source repository URL might be incorrect, unreachable, require SSL authentication, has IP filtering or is non-existent. Tested URLs:

🠶 https://repo.almalinux.org/almalinux/9/crb/$basearch/os

Error details: URL reachability check failed: HTTP response code: 404

🠶 https://repo.almalinux.org/almalinux/9/crb/noarch/os

Error details: URL reachability check failed: HTTP response code: 404

🠶 https://repo.almalinux.org/almalinux/9/crb/x86_64/os

Error details: URL reachability check failed: HTTP response code: 404_

**Comment by lbr38** [comment]
Hi

You're right, thanks for seeing it!

I'll fix it asap.

**Comment by lbr38** [comment]
This is now fixed
