### ISSUE TITLE
Issue mirroring OpenSuse Repos

### ISSUE THREAD

**Issue by gforke97** [lbr38/repomanager#211]
Hello,
I cant seem to mirror the OpenSuse oss Repo because php(?) runs out of allowed memory.
Fatal error occured while running task #45 (you may have to stop the task manually) - Allowed memory size of 1073741824 bytes exhausted (tried to allocate 20480 bytes)
![grafik](https://github.com/user-attachments/assets/fcbbbec7-a5b9-44e6-ad81-5f353fb0f5a5)
![grafik](https://github.com/user-attachments/assets/467018e2-caf2-4247-b17e-6411cefc9f8c)

**Comment by lbr38** [comment]
Yes, you found the right setting to modify.
I reproduced the issue and increased to 2048M but I now have a new error message:

![image](https://github.com/user-attachments/assets/6d9f7297-028f-4598-a0dd-639f2e69e077)

Which means that either the package is "corrupted", either the checksum indicated in the opensuse repo metadata is wrong. May be retry later.

**Comment by lbr38** [comment]
Finally, after investigating, there is a repomanager issue. Checksum of the package is sha512 and repomanager is currently only checking sha256 and sha1. Just let me some time to release a hotfix.
