### ISSUE TITLE
Unable to mirror from rocky vault latest rocky 9.5

### ISSUE THREAD

**Issue by rareshornet** [lbr38/repomanager#214]
Hi, cheers for your project its great!

Rocky vault provides access to the latest versions of the os, currently rocky 9.5 but it seems repomanager is having some difficulties grabbing packages from the 9.5 link:

mirror link example: https://dl.rockylinux.org/vault/rocky/9.5/BaseOS/x86_64/os

I get error code 403 in the task error when repomanager is trying to access the link. The link works in a browser.

It does work with other older versions of rocky like 9.4 for example, I imagine there might be some sort of a redirect going on for rocky 9.5 maybe that repomanager does not follow?!

It's important for me to always look at vault repos as I need to deploy machines in an isolated environment in a controlled fashion with locked repos. Due to the fact that no public mirrors contain older versions of rocky 9 repos what happens at the end of a rocky 9 cycle all files are deleted by public mirrors then my local repos gets cleaned next time its scheduled to run a repoupdate. Mirroring from vault ensures my local repo is not deleted when public mirrors do so.

Cheers!

**Comment by lbr38** [comment]
Hello!

Thanks for the feedback I really appreciate it. 

I checked on my side and you're right https://dl.rockylinux.org/vault/rocky/9.5/BaseOS/x86_64/os is working but https://dl.rockylinux.org/vault/rocky/9.5/BaseOS/x86_64/os/repodata/ is not (returning 403). This repodata directory is required for the mirror to work as it contains the metadata for the packages.

Let me some time to see if there is a workaround, I'll keep you posted.

Thanks!

**Comment by rareshornet** [comment]
Oh i see. Thanks for taking a look, it would be super useful at least for
me to get vault working.

**Comment by lbr38** [comment]
Just found this https://forums.rockylinux.org/t/http-403-error-while-getting-vault-repo-metadata-for-9-3-version/13412/4 

Someone had the same issue with 9.3 back then.

Looks like Rocky team is locking access to the latest version's /repodata directory to prevent mirroring tools from copying the files. I guess you will have to wait for the next version (9.6?) to be released before you can mirror 9.5 through the vault repo.

**Comment by rareshornet** [comment]
Thanks for taking a look. With cobbler I don't have that issue. It grabs
all rpms then makes a local metadata pack. I just didnt want to use cobbler
as your tool is cooler :p

**Comment by lbr38** [comment]
I see :)

Repomanager is not a crawler, for security and reliability reasons it needs to retrieve the metadata from the target repo to know the names of the distributed packages and their checksums. This ensures that the downloaded packages are indeed the expected ones.

This is likely not the case with Cobbler, which, I guess, copies everything without worrying about data consistency.

If you really need the 9.5 packages now, you should mirror them from https://download.rockylinux.org/pub/rocky/$releasever/BaseOS/$basearch/os then go back to the vault repo when a new rocky version is out.
