### ISSUE TITLE
How to finish installation

### ISSUE THREAD

**Issue by FC4Lee** [lbr38/repomanager#87]
there is no settings folder & cant finish install as the promotion saying https://xxx.xxx.xxx.xxx/settings

**Comment by lbr38** [comment]
> there is no settings folder & cant finish install as the promotion saying https://xxx.xxx.xxx.xxx/settings

Hello
Can you provide more informations or logs please?

Are you using nginx and the provided vhost from the documentation?

**Comment by FC4Lee** [comment]
I installed a fresh new debian 11.6 system and didn't install the requirement
then I did this "git clone https://github.com/lbr38/repomanager.git  /tmp/repomanager "
and executed "/tmp/repomanager/repomanager --install"
after I interacted just like the gif animation instructed me without any error information

**Comment by lbr38** [comment]
Please follow all requirements steps and install nginx + PHP8.1 with the recommended vhost.
